CREATE TABLE `sqlyog_connections` (
  `Connection_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  `Host` varchar(255) NOT NULL,
  `User` varchar(255) NOT NULL,
  `StorePassword` tinyint(1) NOT NULL DEFAULT '1',
  `Password` varchar(255) NOT NULL,
  `Port` smallint(5) unsigned NOT NULL,
  `Database` varchar(255) DEFAULT NULL,
  `compressedprotocol` tinyint(1) NOT NULL DEFAULT '0',
  `readonly` tinyint(1) NOT NULL DEFAULT '0',
  `defaulttimeout` tinyint(1) NOT NULL DEFAULT '1',
  `waittimeoutvalue` int(11) NOT NULL DEFAULT '28800',
  `Tunnel` tinyint(1) NOT NULL DEFAULT '0',
  `Http` varchar(512) DEFAULT NULL,
  `HTTPTime` smallint(5) unsigned DEFAULT '30',
  `HTTPuds` tinyint(1) DEFAULT '0',
  `HTTPudsPath` varchar(255) DEFAULT NULL,
  `Is401` tinyint(1) DEFAULT '0',
  `IsProxy` tinyint(1) DEFAULT '0',
  `Proxy` varchar(255) DEFAULT NULL,
  `ProxyUser` varchar(255) DEFAULT NULL,
  `ProxyPwd` varchar(255) DEFAULT NULL,
  `ProxyPort` smallint(5) unsigned DEFAULT '808',
  `401User` varchar(255) DEFAULT NULL,
  `401Pwd` varchar(255) DEFAULT NULL,
  `ContentType` varchar(50) DEFAULT 'text/xml',
  `HttpEncode` tinyint(1) DEFAULT '0',
  `SSH` tinyint(1) DEFAULT '0',
  `SshUser` varchar(255) DEFAULT NULL,
  `SshPwd` varchar(255) DEFAULT NULL,
  `SshHost` varchar(255) DEFAULT NULL,
  `SshPort` smallint(5) unsigned DEFAULT '22',
  `SshForHost` smallint(5) unsigned DEFAULT '22',
  `SshPasswordRadio` tinyint(1) DEFAULT '1',
  `SshPrivateRadio` tinyint(1) DEFAULT '0',
  `SSHPrivateKeyPath` varchar(255) DEFAULT NULL,
  `SshSavePassword` tinyint(1) DEFAULT '1',
  `SslChecked` tinyint(1) DEFAULT '0',
  `SshAuth` tinyint(1) DEFAULT '0',
  `Client_Key` text,
  `Client_Cert` text,
  `CA` text,
  `Cipher` varchar(255) DEFAULT NULL,
  `ObjectbrowserBkcolor` int(10) unsigned DEFAULT '16777215',
  `ObjectbrowserFgcolor` int(10) unsigned DEFAULT '0',
  `sqlmode_global` tinyint(1) DEFAULT '1',
  `sqlmode_value` varchar(255) DEFAULT NULL,
  `init_command` text,
  `keep_alive` tinyint(1) DEFAULT '0',
  `AutocompleteTagbuilded` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`Connection_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1026 DEFAULT CHARSET=utf8mb4